site_name: MapDB
site_url: http://doc.mapdb.org
site_description: Documentation for MapDB database engine.

repo_url: https://github.com/jankotek/mapdb-site
pages:
- ['index.md', 'MapDB']
- ['intro-getting-started.md', 'Intro','Getting started']
- ['db-and-dbmaker.md', 'DB and DBMaker']

- ['faq-general.md', 'Frequently Asked Questions','General']
- ['faq-performance.md', 'Frequently Asked Questions','Performance']
- ['faq-problems.md', 'Frequently Asked Questions','Problems']

- ['transactions.md', 'Transactions']
- ['secondary-collections.md', 'Secondary collections']

- ['caches.md', 'Caches']
- ['queues.md', 'Queues']

- ['htreemap.md', 'HashMap']

- ['internals-quick-intro.md', 'Internals','Internals quick intro']

copyright: Copyright &copy; 2014, <a href="http://www.kotek.net">Jan Kotek</a>.